spring:
  rabbitmq:
    port: 5672

rabbitmq:
  exchange:
    name: scheduled-tasks-exchange

  routingKey:
    analyticsBuilder: analytics-builder-service-task
    vacancyImport: vacancy-import-service-task

vacancyImportScheduledTaskDto:
  pageSize: 100
  pageNumber: 20

management:
  endpoint:
    shutdown:
      enabled: true

application:
  schedule:
    delayMinutes: 60
  queries:
    - Java
    - Python
    - Kotlin